### ISSUE TITLE
Finalize json data schema

### ISSUE THREAD

**Issue by timothyjamesjensen** [new-dev/quick-note#2]
Json data schema needs to be finalized with all of the data we will ever use in the future. Because once the extension is in use, we will not be able to add any data fields.

**Comment by alextappin** [comment]
_ID_ Field so we can no longer pass the index but the id. Allows us to filter.

**Comment by alextappin** [comment]
We can close this. This is no longer an issue. We can change/add different fields to the json as long as we keep checking the other fields.
