### ISSUE TITLE
After you save a note, the url is highlighted on the page... 

### ISSUE THREAD

**Issue by alextappin** [new-dev/quick-note#24]
We shouldn't need to show the user the highlighted url. Minor bug

**Comment by timothyjamesjensen** [comment]
I don't understand what you are addressing here. What highlighted url are we showing? Can you clarify the issue or add a gyazo gif?

**Comment by alextappin** [comment]
I will try to recreate it. It was happening on the main branch a few days ago before we merged the search bar stuff.

**Comment by alextappin** [comment]
looks like I can't seem to recreate it anymore... closed! lol
